import { resume } from "./resume";

const [razerExperience] = resume.experience;

export const timeline = [
  {
    id: "devmatch-hackathon-2024",
    date: "2024-08",
    dateLabel: "August 2024",
    year: "2024",
    title: "Devmatch Hackathon 2024",
    organization: "Asia Pacific University, Malaysia",
    preview: "Transformed Figma designs into responsive Next.js code as a frontend developer.",
    description: "Transformed Figma designs into responsive Next.js code as a frontend developer, contributing to a high-impact hackathon project that pushed the boundaries of innovation.",
    technologies: ["Next.js", "Figma"],
    image: { src: "/events/devmatch-2024-timeline.jpg", alt: "Devmatch Hackathon 2024", width: 1600, height: 1200 },
    kind: "Hackathon",
  },
  {
    id: "eth-uprising-workshop",
    date: "2025-02",
    dateLabel: "February 2025",
    year: "2025",
    title: "ETH Uprising Workshop",
    organization: "Asia Pacific University, Malaysia",
    preview: "Captured the energy of a dynamic blockchain workshop through photography.",
    description: "Captured the energy of a dynamic blockchain workshop through photography, helping participants prepare for a major hackathon with hands-on Ethereum development skills.",
    image: { src: "/events/eth-workshop.jpg", alt: "ETH Uprising Workshop", width: 1280, height: 836 },
    kind: "Workshop",
  },
  {
    id: "razer-internship",
    date: razerExperience.startDate,
    dateLabel: razerExperience.dateLabel,
    year: "2025",
    title: razerExperience.role,
    organization: razerExperience.company,
    preview: "Enhanced .NET web applications, supported testing, and implemented AWS observability during a software engineering internship.",
    description: "Developed and enhanced .NET web application features, supported manual and automated testing, implemented AWS X-Ray observability with CloudWatch, and contributed to release verification, hotfix delivery, and production deployments.",
    technologies: razerExperience.technologies,
    image: { ...razerExperience.image, width: 1280, height: 960 },
    kind: "Experience",
  },
  {
    id: "devmatch-hackathon-2025",
    date: "2025-08",
    dateLabel: "August 2025",
    year: "2025",
    title: "Devmatch Hackathon 2025",
    organization: "Asia Pacific University, Malaysia",
    preview: "Mentored aspiring developers and captured stunning event photos.",
    description: "Mentored aspiring developers and captured stunning event photos, fostering a vibrant tech community while guiding students through technical challenges.",
    image: { src: "/events/devmatch-2025.jpg", alt: "Devmatch Hackathon 2025", width: 882, height: 582 },
    kind: "Hackathon",
  },
  {
    id: "token-2049-singapore-2025",
    date: "2025-09",
    dateLabel: "September 2025",
    year: "2025",
    title: "TOKEN2049 Singapore",
    organization: "TOKEN2049, Singapore",
    preview: "Explored how blockchain companies design products and where decentralised technology creates meaningful value.",
    description: "Attended TOKEN2049 Singapore to study how blockchain companies bring products to market, evaluate where decentralised technology solves real problems, and understand the product, business, and technical decisions behind Web3 adoption.",
    technologies: ["Blockchain", "Web3", "Product Design"],
    image: { src: "/events/Token.jpg", alt: "TOKEN2049 Singapore", width: 1024, height: 768 },
    kind: "Conference",
  },
  {
    id: "great-ai-hackathon-2025",
    date: "2025-10",
    dateLabel: "October 2025",
    year: "2025",
    title: "Great AI Hackathon 2025",
    organization: "Great Malaysia AI Hackathon",
    preview: "Led the StudyHub team to the final round while owning the cloud-backed backend architecture.",
    description: "Led a four-member team and took primary ownership of the backend architecture for StudyHub. Coordinated development work, integrated Cognito, RDS, S3, Route 53, and Amazon Bedrock, and developed the AI-powered learning assistant that generates learning content.",
    technologies: ["Next.js", "AWS Cognito", "RDS", "S3", "Route 53", "Amazon Bedrock"],
    image: { src: "/events/GreatAIHackathon.jpg", alt: "Great AI Hackathon 2025 team", width: 1024, height: 768 },
    kind: "Hackathon",
  },
  {
    id: "final-year-project-showcase-2026",
    date: "2026-06",
    dateLabel: "June 2026",
    year: "2026",
    title: "Final Year Project Showcase",
    organization: "Asia Pacific University, Malaysia",
    preview: "Won 1st Runner-Up for Quietly, a rule-based mobile app for intelligent Do Not Disturb management.",
    description: "Won 1st Runner-Up at the Final Year Project Showcase among more than 100 Software Engineering students for Quietly. The Flutter app automates Do Not Disturb behaviour through configurable rules for time, location, calendar events, activity, and user-defined profiles.",
    technologies: ["Flutter", "Mobile Development", "Notification Management"],
    image: { src: "/events/FYP%20SHOWCASE.jpeg", alt: "Final Year Project Showcase award ceremony", width: 1024, height: 768 },
    kind: "Achievement",
  },
];
